# Generated by Django 2.2.6 on 2020-06-24 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PredictAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=50)),
                ('abandoned_time', models.DateTimeField(max_length=50, null=True)),
                ('start_time', models.DateTimeField(max_length=50, null=True)),
                ('answer_time', models.DateTimeField(max_length=50, null=True)),
                ('resolved', models.CharField(default='N/A', max_length=100)),
                ('resolved_time', models.DateTimeField(max_length=50, null=True)),
                ('abandoned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agent.Issue')),
            ],
        ),
    ]
