# Generated by Django 2.2.6 on 2020-06-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictagent',
            name='abandoned_time',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='predictagent',
            name='resolved_time',
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
